#include "assets.h"
#include "game.h"


const Color blockImage[BLOCK_TYPES][BLOCK_SIZE] = {
    /* IMG_CST */           { 0x0000, 0x0000, 0x92eb, 0xc1c6, 0xb944, 0xba27, 0x51e7, 0x0000, 0x2945, 0x2124, 0x0020, 0x1862, 0x6124, 0xc1a5, 0xb8e1, 0x5208, 0x1082, 0x0000, 0x2081, 0x3922, 0x3122, 0x18a1, 0x88a1, 0x8964, 0x18c3, 0x73f0, 0x736d, 0xa3aa, 0x630c, 0x6b0b, 0x51c3, 0x5061, 0x2945, 0xc77f, 0x6474, 0xd572, 0x865e, 0x7e1d, 0xabaa, 0x6247, 0x0000, 0xc4cf, 0xedb1, 0xe5b2, 0xe5b3, 0xdd51, 0xb40b, 0xee98, 0x0000, 0xa44e, 0xbc6e, 0xabee, 0xfe76, 0xe592, 0x9bcb, 0x2966, 0x0000, 0x1082, 0xbcd0, 0xd530, 0xd531, 0x8b8b, 0x0021, 0x0000 },
    /* IMG_CAGE */          { 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0x0000, 0xc618, 0x2945, 0x0000, 0xc618, 0x0000, 0xc618, 0xc618, 0x0000, 0xc618, 0x0000, 0x0000, 0xc618, 0x0000, 0xc618, 0xc618, 0x0000, 0xc618, 0x0000, 0x0000, 0xc618, 0x0000, 0xc618, 0xc618, 0x0000, 0xc618, 0x0000, 0x0000, 0xc618, 0x0000, 0xc618, 0xc618, 0x0000, 0xc618, 0x0000, 0x0000, 0xc618, 0x0000, 0xc618, 0xc618, 0x0000, 0xc618, 0x0000, 0x10c4, 0xc618, 0x0000, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618, 0xc618 },
    /* IMG_GK */            { 0x0000, 0x0000, 0x9be6, 0xfe84, 0xfe46, 0xfe65, 0x4a24, 0x0000, 0x0000, 0xbca8, 0xfea5, 0x2945, 0x0000, 0x20a4, 0xfec7, 0x0882, 0x2904, 0xff24, 0x1083, 0x8364, 0xf64a, 0x0001, 0x6a44, 0x7b24, 0x8ac5, 0xe5c6, 0x0021, 0xb4a8, 0xff0c, 0xcd8d, 0x49a4, 0xa426, 0xb3a5, 0x8b82, 0xe64e, 0xff0a, 0xfe45, 0x9c05, 0x7ae7, 0x6ac3, 0x9b05, 0xee07, 0x0000, 0x9408, 0xffac, 0x0002, 0xf608, 0x0862, 0x3944, 0xfe64, 0x5aa6, 0x0000, 0x10c4, 0xb4a7, 0xac66, 0x0000, 0x0000, 0x92e8, 0xfdc4, 0xe5c6, 0xfe46, 0x9be6, 0x0000, 0x0000 },
    /* IMG_GK_IN_CAGE */    { 0x738e, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0xbca8, 0x7bef, 0x2945, 0x0000, 0x5aab, 0xfec7, 0x7bef, 0x7bef, 0xff24, 0x7bef, 0x8364, 0xf64a, 0x7bef, 0x6a44, 0x7bef, 0x7bef, 0xe5c6, 0x7bef, 0xb4a8, 0xff0c, 0x7bef, 0x49a4, 0x7bef, 0x7bef, 0x8b82, 0x7bef, 0xff0a, 0xfe45, 0x7bef, 0x7ae7, 0x7bef, 0x7bef, 0xee07, 0x7bef, 0x9408, 0xffac, 0x7bef, 0xf608, 0x7bef, 0x7bef, 0xfe64, 0x7bef, 0x0000, 0x10c4, 0x7bef, 0xac66, 0x7bef, 0x7bef, 0x83ce, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef, 0x7bef },
    /* IMG_CST_ON_CAGE */   { 0x0000, 0x0000, 0x92eb, 0xc1c6, 0xb944, 0xba27, 0xc618, 0xc618, 0x2945, 0x2124, 0x0020, 0x1862, 0x6124, 0xc1a5, 0xb8e1, 0xc618, 0xc618, 0x0000, 0x2081, 0x3922, 0x3122, 0x18a1, 0x88a1, 0x8964, 0xc618, 0x73f0, 0x736d, 0xa3aa, 0x630c, 0x6b0b, 0x51c3, 0x5061, 0xc618, 0xc77f, 0x6474, 0xd572, 0x865e, 0x7e1d, 0xabaa, 0x6247, 0xc618, 0xc4cf, 0xedb1, 0xe5b2, 0xe5b3, 0xdd51, 0xb40b, 0xee98, 0xc618, 0xa44e, 0xbc6e, 0xabee, 0xfe76, 0xe592, 0x9bcb, 0xc618, 0xc618, 0xc618, 0xbcd0, 0xd530, 0xd531, 0x8b8b, 0xc618, 0xc618 },
    /* IMG_TREE */          { 0x0000, 0x0000, 0x0000, 0x3287, 0x4baa, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x3a87, 0x654d, 0xaf12, 0xa58f, 0x0000, 0x0000, 0x0000, 0x0000, 0x536a, 0x6dce, 0x85ee, 0x8c8c, 0x0000, 0x0000, 0x0000, 0x3266, 0x54ab, 0x6d6c, 0x860f, 0x8650, 0x74cc, 0x0000, 0x0000, 0x5b69, 0x8e90, 0x862f, 0x7dee, 0x9e90, 0x9d2d, 0x0000, 0x640c, 0x86b1, 0x6d8e, 0x548b, 0x8650, 0x7e0f, 0x9eb1, 0x9d4e, 0x0000, 0x0000, 0x0000, 0x9b49, 0x9b49, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x9b49, 0x9b49, 0x0000, 0x0000, 0x0000 }
};

const uint64_t blockImageMask[BLOCK_MASK_TYPE] = {
    /* IMG_CST */   0xfcfe7f7f7f7f7e3c,
    /* IMG_CAGE */  0xffa5a5a5a5a5a5ff,
};


const GameState gameLevel1_1 = {
    4, 3, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,   CST, BLANK, BLANK,    GK, BLANK, BLANK,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel1_2 = {
    4, 3, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,   CST, BLANK, BLANK,    GK, BLANK, BLANK,  CAGE,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,    GK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel1_3 = {
    4, 3, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,   CST, BLANK, BLANK,    GK, BLANK, BLANK,  CAGE,  CAGE,    GK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,    GK, BLANK, BLANK,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel2_1 = {
    2, 2, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK,   CST, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,    GK,  TREE,  TREE, BLANK,  TREE, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE,  TREE, BLANK, BLANK, BLANK,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel2_2 = {
    2, 2, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK,   CST, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,    GK,  TREE,  TREE,    GK,  TREE, BLANK,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE,  TREE, BLANK, BLANK, BLANK,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel2_3 = {
    2, 2, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK,   CST, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,    GK,  TREE,  TREE,    GK,  TREE, BLANK,  CAGE,  TREE,  CAGE, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE,  TREE, BLANK, BLANK, BLANK,  CAGE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK,    GK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel3_1 = {
    1, 1, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,   CST, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,    GK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK, BLANK,  TREE,  TREE,  TREE,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK,  TREE,  TREE,  TREE, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        {BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel3_2 = {
    1, 1, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,   CST, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK, BLANK,    GK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK,    GK, BLANK,  TREE,  TREE,  TREE,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK,  TREE,  TREE,  TREE,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        {BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK}
    }
};

const GameState gameLevel3_3 = {
    1, 1, 0,
    {
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,   CST, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK,    GK,    GK,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE, BLANK,    GK, BLANK,  TREE,  TREE,  TREE,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK,  TREE,  TREE,  TREE,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK,  CAGE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE, BLANK, BLANK,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE, BLANK, BLANK, BLANK,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        { TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE,  TREE, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK},
        {BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK, BLANK}
    }
};